[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./" }]

# IMPORTANT: disable forge-lint notes/warnings during merge
lint = false
